const PACKS_SELECT_VALUES_MIN = 4;
const PACKS_SELECT_VALUES_MAX = 100;
const PACKS_SELECT_VALUES_DEFAULT = 8;
const PACKS_SELECT_VALUES_TWENTY = 20;
const PACKS_SELECT_VALUES_MIDDLE = 50;

export const PACKS_SELECT_VALUES = [
    PACKS_SELECT_VALUES_MIN,
    PACKS_SELECT_VALUES_MAX,
    PACKS_SELECT_VALUES_MIDDLE,
    PACKS_SELECT_VALUES_DEFAULT,
    PACKS_SELECT_VALUES_TWENTY,
].sort((a: number, b: number): number => (a < b ? -1 : 1));
