export const CARDS_SELECT_VALUE_MIN = 4;
const CARDS_SELECT_VALUE_TEN = 10;
const CARDS_SELECT_VALUE_MIDDLE = 55;
const CARDS_SELECT_VALUE_MAX = 110;

export const CARDS_SELECT_VALUES = [
    CARDS_SELECT_VALUE_MAX,
    CARDS_SELECT_VALUE_MIDDLE,
    CARDS_SELECT_VALUE_MIN,
    CARDS_SELECT_VALUE_TEN,
].sort((a, b) => a - b);
